name: '[Manual] Build and Deploy All Modules'

on:
  workflow_dispatch:
    inputs:
      target_modules:
        description: 'Select modules to build/deploy (comma-separated: web,vue,front,core,form,batch,card-systems)'
        required: true
        type: string
      action_type:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - build
          - deploy
          - build-and-deploy
      stg_env:
        description: 'Select staging environment'
        required: true
        type: choice
        options:
          - stg1
          - stg2
          - stg3
          - stg4
          - stg5
          - stg6
      batch_stg_env:
        description: 'Select batch staging environment (only for batch module)'
        required: false
        type: choice
        options:
          - stg1
          - stg2
          - stg3
          - stg4
      tag_numbers:
        description: 'Tag numbers for Harbor images (format: module:tag,module:tag e.g., web:123,vue:456)'
        required: false
        type: string
      form_artifact_tag:
        description: 'Tag number for Form module in JFrog'
        required: false
        type: string

jobs:
  echo_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Echo all inputs
        run: |
          echo "Selected modules: ${{ inputs.target_modules }}"
          echo "Action type: ${{ inputs.action_type }}"
          echo "Staging environment: ${{ inputs.stg_env }}"
          echo "Batch staging environment: ${{ inputs.batch_stg_env }}"
          echo "Tag numbers: ${{ inputs.tag_numbers }}"
          echo "Form artifact tag: ${{ inputs.form_artifact_tag }}"

  generate_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_number: ${{ steps.tag_generation.outputs.tag_number }}
    steps:
      - name: Generate tag number
        id: tag_generation
        run: echo "tag_number=${{ github.run_number }}" >> $GITHUB_OUTPUT

  build_card_systems:
    needs: generate_tag
    if: |
      needs.generate_tag.result == 'success' &&
      (!contains(inputs.target_modules, 'vue') ||
        !contains(inputs.target_modules, 'web')) &&
      contains(inputs.action_type, 'build')
    uses: ./.github/workflows/build-card-systems.yaml
    with:
      tag_number: ${{ needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.stg_env }}

  build_core:
    needs: [generate_tag, build_card_systems]
    if: |
      (contains(inputs.target_modules, 'core') ||
      contains(inputs.target_modules, 'form')) && 
      contains(inputs.action_type, 'build') &&
      !contains(inputs.tag_numbers, 'core:')
    uses: ./.github/workflows/build-core.yaml
    with:
      tag_number: ${{ needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.stg_env }}

  build_form:
    needs: [generate_tag, build_core]
    if: |
      contains(inputs.target_modules, 'form') && 
      contains(inputs.action_type, 'build') &&
      inputs.form_artifact_tag == ''
    uses: ./.github/workflows/build-form.yaml
    with:
      tag_number: ${{ needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.stg_env }}

  build_front:
    needs: [generate_tag, build_card_systems]
    if: |
      contains(inputs.target_modules, 'front') && 
      contains(inputs.action_type, 'build') &&
      !contains(inputs.tag_numbers, 'front:')
    uses: ./.github/workflows/build-front.yaml
    with:
      tag_number: ${{ needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.stg_env }}

  build_vue:
    needs: generate_tag
    if: |
      contains(inputs.target_modules, 'vue') && 
      contains(inputs.action_type, 'build') &&
      !contains(inputs.tag_numbers, 'vue:')
    uses: ./.github/workflows/build-vue.yaml
    with:
      tag_number: ${{ needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.stg_env }}

  build_web:
    needs: generate_tag
    if: |
      contains(inputs.target_modules, 'web') && 
      contains(inputs.action_type, 'build') &&
      !contains(inputs.tag_numbers, 'web:')
    uses: ./.github/workflows/build-web.yaml
    with:
      tag_number: ${{ needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.stg_env }}

  build_batch:
    needs: [generate_tag, build_card_systems]
    if: |
      contains(inputs.target_modules, 'batch') && 
      contains(inputs.action_type, 'build') &&
      !contains(inputs.tag_numbers, 'batch:')
    uses: ./.github/workflows/build-batch.yaml
    with:
      tag_number: ${{ needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.batch_stg_env }}

  deploy_web_vue_front_core:
    needs: [generate_tag, build_web, build_vue, build_front, build_core]
    if: |
      !failure() &&
      needs.generate_tag.result == 'success' &&
      (contains(inputs.target_modules, 'web') ||
        contains(inputs.target_modules, 'vue') ||
        contains(inputs.target_modules, 'front') ||
        contains(inputs.target_modules, 'core')) &&
      contains(inputs.action_type, 'deploy')
    uses: ./.github/workflows/deploy-web-vue-front-core.yaml
    with:
      tag_numbers: ${{ inputs.tag_numbers }}
      default_tag: ${{ needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.stg_env }}

  deploy_form:
    needs: [generate_tag, build_form]
    if: |
      !failure() && 
      needs.generate_tag.result == 'success' &&
      (contains(inputs.target_modules, 'form') && contains(inputs.action_type, 'deploy'))
    uses: ./.github/workflows/deploy-form.yaml
    with:
      tag_number: ${{ inputs.form_artifact_tag != '' && inputs.form_artifact_tag || needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.stg_env }}

  deploy_batch:
    needs: [generate_tag, build_batch]
    if: |
      !failure() &&
      needs.generate_tag.result == 'success' &&
      (contains(inputs.target_modules, 'batch') && contains(inputs.action_type, 'deploy'))
    uses: ./.github/workflows/deploy-batch.yaml
    with:
      tag_number: ${{ inputs.batch_action == 'deploy' && inputs.batch_tag_number || needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.batch_stg_env }}

  deploy_card_systems:
    needs: [generate_tag, build_card_systems]
    if: |
      !failure() &&
      needs.generate_tag.result == 'success' &&
      (contains(inputs.target_modules, 'card-systems') && contains(inputs.action_type, 'deploy'))
    uses: ./.github/workflows/deploy-card-systems.yaml
    with:
      tag_number: ${{ inputs.card_systems_action == 'deploy' && inputs.card_systems_tag_number || needs.generate_tag.outputs.tag_number }}
      environment: ${{ inputs.stg_env }}
