name: Build and Deploy Modules

on:
  workflow_dispatch:
    inputs:
      target_modules:
        description: 'Select modules to build/deploy (comma-separated: web,vue,front,core,form,batch,card-systems)'
        required: true
        type: string
      action_type:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - build
          - deploy
          - build-and-deploy
      stg_env:
        description: 'Select staging environment'
        required: true
        type: choice
        options:
          - stg1
          - stg2
          - stg3
          - stg4
          - stg5
          - stg6
      batch_stg_env:
        description: 'Select batch staging environment (only for batch module)'
        required: false
        type: choice
        options:
          - stg1
          - stg2
          - stg3
          - stg4
      tag_numbers:
        description: 'Tag numbers for deployment (format: module:tag,module:tag e.g., web:123,vue:456)'
        required: false
        type: string

jobs:
  generate_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_number: ${{ steps.tag_generation.outputs.tag_number }}
    steps:
      - name: Generate tag number
        id: tag_generation
        run: echo "tag_number=${{ github.run_number }}" >> $GITHUB_OUTPUT

  build_card_systems:
    needs: generate_tag
    runs-on: ubuntu-latest
    if: contains(inputs.target_modules, 'card-systems') && contains(inputs.action_type, 'build')
    steps:
      - name: Build card-systems
        uses: ./github/workflows/build-card-systems.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_core:
    needs: [generate_tag, build_card_systems]
    runs-on: ubuntu-latest
    if: contains(inputs.target_modules, 'core') && contains(inputs.action_type, 'build')
    steps:
      - name: Build core
        uses: ./github/workflows/build-core.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_form:
    needs: [generate_tag, build_core]
    runs-on: ubuntu-latest
    if: contains(inputs.target_modules, 'form') && contains(inputs.action_type, 'build')
    steps:
      - name: Build form
        uses: ./github/workflows/build-form.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_front:
    needs: [generate_tag, build_card_systems]
    runs-on: ubuntu-latest
    if: contains(inputs.target_modules, 'front') && contains(inputs.action_type, 'build')
    steps:
      - name: Build front
        uses: ./github/workflows/build-front.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_vue:
    needs: generate_tag
    runs-on: ubuntu-latest
    if: contains(inputs.target_modules, 'vue') && contains(inputs.action_type, 'build')
    steps:
      - name: Build vue
        uses: ./github/workflows/build-vue.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_web:
    needs: generate_tag
    runs-on: ubuntu-latest
    if: contains(inputs.target_modules, 'web') && contains(inputs.action_type, 'build')
    steps:
      - name: Build web
        uses: ./github/workflows/build-web.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_batch:
    needs: [generate_tag, build_card_systems]
    runs-on: ubuntu-latest
    if: contains(inputs.target_modules, 'batch') && contains(inputs.action_type, 'build')
    steps:
      - name: Build batch
        uses: ./github/workflows/build-batch.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.batch_stg_env }}

  deploy_web_vue_front_core:
    needs: [generate_tag, build_web, build_vue, build_front, build_core]
    runs-on: ubuntu-latest
    if: |
      !failure() && 
      needs.generate_tag.result == 'success'
    steps:
      - name: Get tag numbers
        id: get_tags
        run: |
          # タグ番号を取得する関数
          # 引数: モジュール名
          # 戻り値: 指定されたタグ番号、または生成されたタグ番号
          get_tag_number() {
            local module=$1
            local tag_numbers="${{ inputs.tag_numbers }}"
            local default_tag="${{ needs.generate_tag.outputs.tag_number }}"
            
            # モジュール名:タグ番号 の形式で指定されているか確認
            if [[ $tag_numbers == *"$module:"* ]]; then
              # タグ番号を抽出 (例: "web:123,vue:456" から "123" を取得)
              echo "$tag_numbers" | grep -o "$module:[^,]*" | cut -d':' -f2
            else
              # 指定がない場合はデフォルトのタグ番号を使用
              echo "$default_tag"
            fi
          }

          # 各モジュールのタグ番号を取得してoutputに設定
          echo "web_tag=$(get_tag_number 'web')" >> $GITHUB_OUTPUT
          echo "vue_tag=$(get_tag_number 'vue')" >> $GITHUB_OUTPUT
          echo "front_tag=$(get_tag_number 'front')" >> $GITHUB_OUTPUT
          echo "core_tag=$(get_tag_number 'core')" >> $GITHUB_OUTPUT

      - name: Deploy web
        if: contains(inputs.target_modules, 'web') && contains(inputs.action_type, 'deploy')
        uses: ./github/workflows/deploy-web-vue-front-core.yaml
        with:
          tag_number: ${{ steps.get_tags.outputs.web_tag }}
          environment: ${{ inputs.stg_env }}

      - name: Deploy vue
        if: contains(inputs.target_modules, 'vue') && contains(inputs.action_type, 'deploy')
        uses: ./github/workflows/deploy-web-vue-front-core.yaml
        with:
          tag_number: ${{ steps.get_tags.outputs.vue_tag }}
          environment: ${{ inputs.stg_env }}

      - name: Deploy front
        if: contains(inputs.target_modules, 'front') && contains(inputs.action_type, 'deploy')
        uses: ./github/workflows/deploy-web-vue-front-core.yaml
        with:
          tag_number: ${{ steps.get_tags.outputs.front_tag }}
          environment: ${{ inputs.stg_env }}

      - name: Deploy core
        if: contains(inputs.target_modules, 'core') && contains(inputs.action_type, 'deploy')
        uses: ./github/workflows/deploy-web-vue-front-core.yaml
        with:
          tag_number: ${{ steps.get_tags.outputs.core_tag }}
          environment: ${{ inputs.stg_env }}

  deploy_form:
    needs: [generate_tag, build_form]
    runs-on: ubuntu-latest
    if: |
      !failure() && 
      needs.generate_tag.result == 'success'
    steps:
      - name: Deploy form
        if: contains(inputs.target_modules, 'form') && contains(inputs.action_type, 'deploy')
        uses: ./github/workflows/deploy-form.yaml
        with:
          tag_number: ${{ steps.get_tags.outputs.form_tag }}
          environment: ${{ inputs.stg_env }}

  deploy_batch:
    needs: [generate_tag, build_batch]
    runs-on: ubuntu-latest
    if: |
      !failure() && 
      needs.generate_tag.result == 'success'
    steps:
      - name: Deploy batch
        if: contains(inputs.target_modules, 'batch') && contains(inputs.action_type, 'deploy')
        uses: ./github/workflows/deploy-batch.yaml
        with:
          tag_number: ${{ steps.get_tags.outputs.batch_tag }}
          environment: ${{ inputs.stg_env }}

  deploy_card_systems:
    needs: [generate_tag, build_card_systems]
    runs-on: ubuntu-latest
    if: |
      !failure() && 
      needs.generate_tag.result == 'success'
    steps:
      - name: Deploy card-systems
        if: contains(inputs.target_modules, 'card-systems') && contains(inputs.action_type, 'deploy')
        uses: ./github/workflows/deploy-card-systems.yaml
        with:
          tag_number: ${{ steps.get_tags.outputs.card_systems_tag }}
          environment: ${{ inputs.stg_env }}
