name: Build and Deploy Modules

on:
  workflow_dispatch:
    inputs:
      modules:
        description: 'Select modules to build/deploy'
        required: true
        type: choice
        options:
          - web
          - vue
          - front
          - core
          - form
          - batch
          - card-systems
      web_action:
        description: 'web action'
        required: true
        type: choice
        options:
          - build
          - deploy
          - build-and-deploy
          - skip
      vue_action:
        description: 'vue action'
        required: true
        type: choice
        options:
          - build
          - deploy
          - build-and-deploy
          - skip
      front_action:
        description: 'front action'
        required: true
        type: choice
        options:
          - build
          - deploy
          - build-and-deploy
          - skip
      core_action:
        description: 'core action'
        required: true
        type: choice
        options:
          - build
          - deploy
          - build-and-deploy
          - skip
      form_action:
        description: 'form action'
        required: true
        type: choice
        options:
          - build
          - deploy
          - build-and-deploy
          - skip
      batch_action:
        description: 'batch action'
        required: true
        type: choice
        options:
          - build
          - deploy
          - build-and-deploy
          - skip
      card_systems_action:
        description: 'card-systems action'
        required: true
        type: choice
        options:
          - build
          - deploy
          - build-and-deploy
          - skip
      stg_env:
        description: 'Select staging environment'
        required: true
        type: choice
        options:
          - stg1
          - stg2
          - stg3
          - stg4
          - stg5
          - stg6
      batch_stg_env:
        description: 'Select batch staging environment'
        required: true
        type: choice
        options:
          - stg1
          - stg2
          - stg3
          - stg4
      web_tag_number:
        description: 'Tag number for web deployment (if deploy only)'
        required: false
        type: string
        default: ''
      vue_tag_number:
        description: 'Tag number for vue deployment (if deploy only)'
        required: false
        type: string
        default: ''
      front_tag_number:
        description: 'Tag number for front deployment (if deploy only)'
        required: false
        type: string
        default: ''
      core_tag_number:
        description: 'Tag number for core deployment (if deploy only)'
        required: false
        type: string
        default: ''
      form_tag_number:
        description: 'Tag number for form deployment (if deploy only)'
        required: false
        type: string
        default: ''
      batch_tag_number:
        description: 'Tag number for batch deployment (if deploy only)'
        required: false
        type: string
        default: ''
      card_systems_tag_number:
        description: 'Tag number for card-systems deployment (if deploy only)'
        required: false
        type: string
        default: ''

jobs:
  generate_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_number: ${{ steps.tag_generation.outputs.tag_number }}
    steps:
      - name: Generate tag number
        id: tag_generation
        run: echo "tag_number=${{ github.run_number }}" >> $GITHUB_OUTPUT

  build_card_systems:
    needs: generate_tag
    runs-on: ubuntu-latest
    if: contains(inputs.card_systems_action, 'build')
    steps:
      - name: Build card-systems
        uses: ./workflows/build-card-systems.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_core:
    needs: [generate_tag, build_card_systems]
    runs-on: ubuntu-latest
    if: contains(inputs.core_action, 'build')
    steps:
      - name: Build core
        uses: ./workflows/build-core.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_form:
    needs: [generate_tag, build_core]
    runs-on: ubuntu-latest
    if: contains(inputs.form_action, 'build')
    steps:
      - name: Build form
        uses: ./workflows/build-form.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_front:
    needs: [generate_tag, build_card_systems]
    runs-on: ubuntu-latest
    if: contains(inputs.front_action, 'build')
    steps:
      - name: Build front
        uses: ./workflows/build-front.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_vue:
    needs: generate_tag
    runs-on: ubuntu-latest
    if: contains(inputs.vue_action, 'build')
    steps:
      - name: Build vue
        uses: ./workflows/build-vue.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_web:
    needs: generate_tag
    runs-on: ubuntu-latest
    if: contains(inputs.web_action, 'build')
    steps:
      - name: Build web
        uses: ./workflows/build-web.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  build_batch:
    needs: [generate_tag, build_card_systems]
    runs-on: ubuntu-latest
    if: contains(inputs.batch_action, 'build')
    steps:
      - name: Build batch
        uses: ./workflows/build-batch.yaml
        with:
          tag_number: ${{ needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.batch_stg_env }}

  deploy_web_vue_front_core:
    needs: [generate_tag, build_web, build_vue, build_front, build_core]
    runs-on: ubuntu-latest
    if: |
      !failure() && 
      needs.generate_tag.result == 'success'  # タグ番号は必須なのでgenerate_tagは必ず成功している必要がある
    steps:
      - name: Deploy web
        if: contains(inputs.web_action, 'deploy')
        uses: ./workflows/deploy-web-vue-front-core.yaml
        with:
          tag_number: ${{ inputs.web_action == 'deploy' && inputs.web_tag_number || needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

      - name: Deploy vue
        if: contains(inputs.vue_action, 'deploy')
        uses: ./workflows/deploy-web-vue-front-core.yaml
        with:
          tag_number: ${{ inputs.vue_action == 'deploy' && inputs.vue_tag_number || needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

      - name: Deploy front
        if: contains(inputs.front_action, 'deploy')
        uses: ./workflows/deploy-web-vue-front-core.yaml
        with:
          tag_number: ${{ inputs.front_action == 'deploy' && inputs.front_tag_number || needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

      - name: Deploy core
        if: contains(inputs.core_action, 'deploy')
        uses: ./workflows/deploy-web-vue-front-core.yaml
        with:
          tag_number: ${{ inputs.core_action == 'deploy' && inputs.core_tag_number || needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  deploy_form:
    needs: [generate_tag, build_form]
    runs-on: ubuntu-latest
    if: |
      !failure() && 
      needs.generate_tag.result == 'success'
    steps:
      - name: Deploy form
        if: contains(inputs.form_action, 'deploy')
        uses: ./workflows/deploy-form.yaml
        with:
          tag_number: ${{ inputs.form_action == 'deploy' && inputs.form_tag_number || needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}

  deploy_batch:
    needs: [generate_tag, build_batch]
    runs-on: ubuntu-latest
    if: |
      !failure() && 
      needs.generate_tag.result == 'success'
    steps:
      - name: Deploy batch
        if: contains(inputs.batch_action, 'deploy')
        uses: ./workflows/deploy-batch.yaml
        with:
          tag_number: ${{ inputs.batch_action == 'deploy' && inputs.batch_tag_number || needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.batch_stg_env }}

  deploy_card_systems:
    needs: [generate_tag, build_card_systems]
    runs-on: ubuntu-latest
    if: |
      !failure() && 
      needs.generate_tag.result == 'success'
    steps:
      - name: Deploy card-systems
        if: contains(inputs.card_systems_action, 'deploy')
        uses: ./workflows/deploy-card-systems.yaml
        with:
          tag_number: ${{ inputs.card_systems_action == 'deploy' && inputs.card_systems_tag_number || needs.generate_tag.outputs.tag_number }}
          environment: ${{ inputs.stg_env }}
