name: '[Manual] Build and Deploy Batch'

on:
  workflow_dispatch:
    inputs:
      card_apply_batch_branch:
        description: 'Card Apply Batch Branch (format: prototype/apply/stg1/XXX)'
        required: true
        type: string
      card_systems_branch:
        description: 'Card Systems Branch'
        required: true
        type: string
        default: 'master'
      action_type:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - build
          - deploy
          - build-and-deploy
      tag_numbers:
        description: 'Tag numbers for Harbor images (format: module:tag,module:tag e.g., web:123,vue:456)'
        required: false
        type: string


jobs:
  echo_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Echo all inputs
        run: |
          echo "Card Apply Batch Branch: ${{ inputs.card_apply_batch_branch }}"
          echo "Card Systems Branch: ${{ inputs.card_systems_branch }}"
          echo "Action type: ${{ inputs.action_type }}"
          echo "Tag numbers: ${{ inputs.tag_numbers }}"

  get_environment:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.get_envt.outputs.env }}
    steps:
      - name: Extract environment from branch name
        id: get_envt
        run: |
          BRANCH="${{ inputs.card_apply_batch_branch }}"
          ENV=$(echo $BRANCH | grep -oP 'stg[1-4]' || echo '')
          echo "env=$ENV" >> $GITHUB_OUTPUT

  generate_tag:
    needs: get_environment
    runs-on: ubuntu-latest
    outputs:
      tag_number: ${{ steps.tag_generation.outputs.tag_number }}
    steps:
      - name: Generate tag number
        id: tag_generation
        run: echo "tag_number=${{ github.run_number }}" >> $GITHUB_OUTPUT
  
  build_card_systems:
    needs: [generate_tag, get_environment]
    if: needs.generate_tag.result == 'success'
    uses: ./.github/workflows/build-card-systems.yaml
    with:
      tag_number: ${{ needs.generate_tag.outputs.tag_number }}
      branch: ${{ inputs.card_systems_branch }}
      environment: ${{ needs.get_environment.outputs.env }}

  build_batch:
    needs: [generate_tag, build_card_systems]
    if: |
      contains(inputs.action_type, 'build') &&
      !contains(inputs.tag_numbers, 'batch:')
    uses: ./.github/workflows/build-batch.yaml
    with:
      tag_number: ${{ needs.generate_tag.outputs.tag_number }}
      environment: ${{ needs.get_environment.outputs.env }}
      card_apply_batch_branch: ${{ inputs.card_apply_batch_branch }}

  deploy_batch:
    needs: [generate_tag, build_batch]
    if: |
      !failure() &&
      needs.generate_tag.result == 'success' &&
      (contains(inputs.target_modules, 'batch') && contains(inputs.action_type, 'deploy'))
    uses: ./.github/workflows/deploy-batch.yaml
    with:
      tag_number: ${{ inputs.batch_action == 'deploy' && inputs.batch_tag_number || needs.generate_tag.outputs.tag_number }}
      environment: ${{ needs.get_environment.outputs.env }}
