name: Build Batch Module
on:
  workflow_call:
    inputs:
      tag_number:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo parameters
        run: |
          echo "Building batch module with tag: ${{ inputs.tag_number }}"
          echo "Target environment: ${{ inputs.environment }}" 