name: Build Core Module
on:
  workflow_call:
    inputs:
      tag_number:
        required: true
        type: string
      card_apply_branch:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 3 minutes
        run: sleep 180
        
      - name: Echo parameters
        run: |
          echo "Building core module with tag: ${{ inputs.tag_number }}"
          echo "Branch: ${{ inputs.card_apply_branch }}"
          echo "Target environment: ${{ inputs.environment }}" 
