name: Build Card Systems Module
on:
  workflow_call:
    inputs:
      tag_number:
        required: true
        type: string
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo parameters
        run: |
          echo "Building card-systems module with tag: ${{ inputs.tag_number }}"
          echo "Branch: ${{ inputs.branch }}"
          echo "Target environment: ${{ inputs.environment }}" 