name: Manual Build & Deploy

on:
  workflow_dispatch:
    inputs:
      front_action:
        type: choice
        description: 'Front action'
        required: true
        default: 'none'
        options:
          - none
          - build and deploy
          - build
          - deploy
      core_action:
        type: choice
        description: 'Core action'
        required: true
        default: 'none'
        options:
          - none
          - build and deploy
          - build
          - deploy
      vue_action:
        type: choice
        description: 'Vue action'
        required: true
        default: 'none'
        options:
          - none
          - build and deploy
          - build
          - deploy

jobs:
  set-run-number:
    runs-on: ubuntu-latest
    outputs:
      run_number: ${{ steps.set-number.outputs.run_number }}
    steps:
      - id: set-number
        run: echo "run_number=${{ github.run_number }}" >> $GITHUB_OUTPUT

  front-build:
    needs: set-run-number
    if: ${{ github.event.inputs.front_action == 'build' || github.event.inputs.front_action == 'build and deploy' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Front build process with run number ${{ needs.set-run-number.outputs.run_number }}"

  core-build:
    needs: set-run-number
    if: ${{ github.event.inputs.core_action == 'build' || github.event.inputs.core_action == 'build and deploy' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Core build process with run number ${{ needs.set-run-number.outputs.run_number }}"

  vue-build:
    needs: [set-run-number, front-build]
    if: ${{ github.event.inputs.vue_action == 'build' || github.event.inputs.vue_action == 'build and deploy' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Vue build process with run number ${{ needs.set-run-number.outputs.run_number }}"

  deploy:
    needs: [front-build, core-build, vue-build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Front
        if: ${{ github.event.inputs.front_action == 'deploy' || github.event.inputs.front_action == 'build and deploy' }}
        run: echo "Front deploy process with run number ${{ needs.set-run-number.outputs.run_number }}"
      
      - name: Deploy Core
        if: ${{ github.event.inputs.core_action == 'deploy' || github.event.inputs.core_action == 'build and deploy' }}
        run: echo "Core deploy process with run number ${{ needs.set-run-number.outputs.run_number }}"
      
      - name: Deploy Vue
        if: ${{ github.event.inputs.vue_action == 'deploy' || github.event.inputs.vue_action == 'build and deploy' }}
        run: echo "Vue deploy process with run number ${{ needs.set-run-number.outputs.run_number }}"


